apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reactweb-database
  namespace: reactweb
spec:
  targetNamespace: reactweb-staging
  values:
    controllers:
      main:
        replicas: 1
        containers:
          main:
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
    persistence:
      data:
        size: 5Gi
