apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reactweb-processing
  namespace: reactweb
spec:
  targetNamespace: reactweb-prod
  values:
    controllers:
      main:
        replicas: 1
        containers:
          main:
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 250m
                memory: 256Mi
