const COMMON = {
  APP_TITLE: 'Boilerplate App',
  BTN_LOGIN_TEXT: 'Sign In',
  BTN_LOGIN_ARIA_LABEL: 'Navigate to login page',
  BTN_LOGOUT_TEXT: 'Sign Out',
  BTN_LOGOUT_ARIA_LABEL: 'Sign out of application',
  BTN_CLOSE: 'Close',
  BTN_CLOSE_ARIA_LABEL: 'Close dialog or modal',
  BTN_DISMISS_ARIA_LABEL: 'Dismiss notification',
  LABEL_DARK_MODE: 'Dark Mode',
  SWITCH_THEME_ARIA_LABEL: 'Toggle dark mode',
  BADGE_DEFAULT_USER: 'User',
  LABEL_STATUS_AUTH: 'Authentication Status',
  TXT_STATUS_AUTHENTICATED: 'Authenticated',
  TXT_STATUS_NOT_AUTHENTICATED: 'Not Authenticated',
  TXT_NONE: 'None',
} as const;

const SIDEBAR = {
  ...COMMON,
  HEADING_TITLE: COMMON.APP_TITLE,
  NAV_MAIN_ARIA_LABEL: 'Main navigation',
  BTN_CLOSE_ARIA_LABEL: 'Close sidebar',
  BADGE_ADMIN: 'ADMIN',
} as const;

const HEADER = {
  ...COMMON,
  BTN_OPEN_SIDEBAR_ARIA_LABEL: 'Open sidebar',
  BTN_TOGGLE_THEME_ARIA_LABEL: COMMON.SWITCH_THEME_ARIA_LABEL,
  BTN_COMMAND_PALETTE_ARIA_LABEL: 'Open command palette',
  BTN_SHORTCUTS_ARIA_LABEL: 'View keyboard shortcuts',
  INPUT_SEARCH_PLACEHOLDER: 'Search or press Ctrl+K...',
  KBD_SEARCH_SHORTCUT: 'Ctrl+K',
} as const;

const COMMAND_PALETTE = {
  HEADING_TITLE: 'Command Palette',
  INPUT_SEARCH_PLACEHOLDER: 'Type a command or search views...',
  TXT_NO_RESULTS: 'No matching commands found',
  TXT_CATEGORY_NAVIGATION: 'Navigation',
  TXT_CATEGORY_ACTIONS: 'Quick Actions',
  TXT_CATEGORY_APPEARANCE: 'Theme & Appearance',
  TXT_FOOTER_HINT: 'Use arrows to navigate, Enter to select, Esc to close',
  BTN_CLOSE_ARIA_LABEL: 'Close command palette',
  CMD_THEME_LIGHT: 'Switch to Light Mode',
  CMD_THEME_DARK: 'Switch to Dark Mode',
  CMD_SET_ACCENT_PREFIX: 'Set Accent: ',
  CMD_COPY_URL: 'Copy Current Page URL',
  CMD_EXPORT_SENTINEL: 'Export Microsoft Sentinel Security Log',
  CMD_SIMULATE_ALERT: 'Simulate Defender Security Alert',
  CMD_RESET_STORAGE: 'Reset Local Storage Cache',
  KBD_ESC: 'Esc',
} as const;

const SHORTCUTS = {
  HEADING_TITLE: 'Keyboard Shortcuts',
  TXT_DESCRIPTION: 'Speed up your workflow with these quick keyboard shortcuts.',
  LABEL_GLOBAL_SECTION: 'Global Navigation & Tools',
  LABEL_SHORTCUT_PALETTE: 'Open command palette',
  LABEL_SHORTCUT_SHORTCUTS: 'Show keyboard shortcuts',
  LABEL_SHORTCUT_THEME: COMMON.SWITCH_THEME_ARIA_LABEL,
  LABEL_SHORTCUT_GO_HOME: 'Jump to Homepage',
  LABEL_SHORTCUT_GO_SETTINGS: 'Jump to Settings',
  LABEL_SHORTCUT_GO_MICROSOFT: 'Jump to Microsoft Security',
  LABEL_SHORTCUT_GO_DEBUG: 'Jump to Debug (Admin)',
  LABEL_SHORTCUT_GO_LOGIN: 'Jump to Login',
  LABEL_SHORTCUT_CLOSE: COMMON.BTN_CLOSE_ARIA_LABEL,
  TXT_FOOTER_NOTE: 'Productivity Hotkeys',
  BTN_CLOSE: 'Got It',
  BTN_CLOSE_ARIA_LABEL: 'Close keyboard shortcuts modal',
} as const;

const TOAST = {
  BTN_DISMISS_ARIA_LABEL: COMMON.BTN_DISMISS_ARIA_LABEL,
  CONTAINER_ARIA_LABEL: 'Notifications',
  TXT_THEME_DARK: 'Switched to Dark Mode',
  TXT_THEME_LIGHT: 'Switched to Light Mode',
  TXT_ACCENT_CHANGED: 'Accent palette updated to',
  TXT_URL_COPIED: 'Page link copied to clipboard',
  TXT_STORAGE_CLEARED: 'Local storage cache cleared',
  TXT_LOGGED_IN: 'Authenticated successfully',
  TXT_LOGGED_OUT: 'Signed out successfully',
} as const;

const HOMEPAGE = {
  NAV_ID: 'homepage',
  NAV_TITLE: 'Homepage',
  NAV_HASH: '#homepage',
  HEADING_PAGE: 'Welcome to the Homepage',
  TXT_DESCRIPTION: 'This is the default landing view of the application boilerplate.',
  GREETING_MORNING: 'Good morning',
  GREETING_AFTERNOON: 'Good afternoon',
  GREETING_EVENING: 'Good evening',
  HEADING_QUICK_ACTIONS: 'Quick Actions',
  HEADING_SYSTEM_PULSE: 'System Pulse',
  LABEL_STATUS_AUTH: COMMON.LABEL_STATUS_AUTH,
  TXT_STATUS_AUTHENTICATED: COMMON.TXT_STATUS_AUTHENTICATED,
  TXT_STATUS_NOT_AUTHENTICATED: COMMON.TXT_STATUS_NOT_AUTHENTICATED,
  LABEL_STATUS_THEME: 'Theme Mode',
  LABEL_STATUS_ACCENT: 'Accent Palette',
  BTN_QUICK_SETTINGS: 'Settings',
  BTN_QUICK_PALETTE: 'Command Palette',
  BTN_QUICK_COPY_LINK: 'Copy Page Link',
  BTN_QUICK_DEBUG: 'System Diagnostics',
  TXT_HOTKEY_PALETTE: 'Ctrl + K Palette',
  TXT_QUICK_ACTIONS_DESC: 'Tactical command triggers and workflow accelerators.',
} as const;

const SETTINGS = {
  NAV_ID: 'settings',
  NAV_TITLE: 'Settings',
  NAV_HASH: '#settings',
  HEADING_PAGE: 'Settings',
  TXT_DESCRIPTION: 'Configure and customize your application settings and preferences.',
  HEADING_APPEARANCE: 'Appearance & Accent Palette',
  TXT_APPEARANCE_DESC: 'Select your preferred accent theme color across all buttons, tabs, and focus rings.',
  LABEL_ACCENT_PICKER: 'Accent Theme',
  HEADING_FEEDBACK: 'Interactive Feedback & Toasts',
  TXT_FEEDBACK_DESC: 'Test and preview the tactile feedback systems built into the application.',
  BTN_TEST_TOAST: 'Trigger Toast',
  TXT_TEST_TOAST_MESSAGE: 'Here is a toast notification with tactile feedback!',
  TXT_TEST_TOAST_DESC: 'Tactile micro-animations and WCAG-compliant status notifications.',
  TXT_FEEDBACK_NOTE: 'Notifications provide instant visual confirmation for authentication, settings changes, and productivity timers.',
  HEADING_KEYBOARD_CARD: 'Shortcuts Quick-Reference',
  TXT_KEYBOARD_DESC: 'Press the question mark key anytime to inspect all available hotkeys.',
  BTN_VIEW_SHORTCUTS: 'Open Shortcuts Modal',
  LABEL_ALL_SHORTCUTS: 'All Shortcuts Cheatsheet',
  KBD_PALETTE: 'Ctrl + K',
  KBD_THEME: 'T',
  KBD_HELP: '?',
} as const;

const LOGIN = {
  NAV_ID: 'login',
  NAV_TITLE: 'Login',
  NAV_HASH: '#login',
  HEADING_PAGE: 'User Authentication',
  TXT_DESCRIPTION: 'Enter your credentials to access protected diagnostic views.',
  LABEL_USERNAME: 'Username',
  LABEL_PASSWORD: 'Password',
  INPUT_PLACEHOLDER_USERNAME: 'Enter username',
  INPUT_PLACEHOLDER_PASSWORD: 'Enter password',
  BTN_SUBMIT: COMMON.BTN_LOGIN_TEXT,
  BTN_SUBMIT_LOADING: 'Deriving Cryptographic Credentials...',
  BTN_LOGOUT: COMMON.BTN_LOGOUT_TEXT,
  BTN_GO_TO_DEBUG: 'Open Debug View',
  TXT_AUTH_NOTICE: 'Please provide your authorized credentials to proceed.',
  TXT_INVALID_CREDENTIALS: 'Invalid username or password. Please try again.',
  TXT_LOGGED_IN_GREETING: 'You are authenticated as',
  TXT_DEBUG_UNLOCKED: 'Diagnostic console unmasked in tactical navigation.',
  BTN_CLEAR_STORAGE: 'Clear Local Storage',
  BTN_CLEAR_STORAGE_ARIA_LABEL: 'Clear stored session and preferences from local storage',
} as const;

const DEBUG = {
  NAV_ID: 'debug',
  NAV_TITLE: 'Debug',
  NAV_HASH: '#debug',
  HEADING_PAGE: 'Debug & Runtime Diagnostics',
  TXT_DESCRIPTION: 'Protected view for inspecting runtime state, environment variables, and system metrics.',
  HEADING_UNAUTHORIZED: 'Authentication Required',
  TXT_UNAUTHORIZED_MESSAGE: 'You must be authenticated to access the diagnostics dashboard.',
  BTN_LOGIN_PROMPT: 'Go to Login',
  HEADING_SYSTEM_INFO: 'System & Framework',
  HEADING_ACTIVE_STATE: 'Application State',
  LABEL_ACTIVE_ANCHOR: 'Active URL Anchor',
  LABEL_AUTH_STATE: COMMON.LABEL_STATUS_AUTH,
  LABEL_AUTH_ACTIVE: 'Active (True)',
  LABEL_REGISTERED_VIEWS: 'Registered Views Count',
  TXT_AUTH_USER_PREFIX: 'Authenticated: ',
  LABEL_FRAMEWORK: 'Framework',
  VAL_FRAMEWORK: 'React 19.x',
  LABEL_BUILD_TOOL: 'Build Tool',
  VAL_BUILD_TOOL: 'Vite 8.x',
  LABEL_CSS_ENGINE: 'CSS Engine',
  VAL_CSS_ENGINE: 'Tailwind CSS v4',
  LABEL_ROUTING_MODE: 'Routing Mode',
  VAL_ROUTING_MODE: 'Anchor Hash',
  LABEL_SESSION_DURATION: 'Session Duration',
  VAL_SESSION_DURATION: '7 Days',
  HEADING_DEBUG_ACTIONS: 'Tactical Diagnostics & Overrides',
  BTN_LOGOUT_LOCK: 'Terminate Session & Lock Diagnostic Console',
} as const;

const MICROSOFT = {
  NAV_ID: 'microsoft',
  NAV_TITLE: 'Microsoft Security',
  NAV_HASH: '#microsoft',
  HEADING_PAGE: 'Terrain Posture Scores',

  TAB_TILES: 'Tiles',
  TAB_CHARTS: 'Chart',
  TAB_TABLE: 'List',

  LABEL_BUBBLES_SECTION: 'Active Telemetry Signals',
  LABEL_BUBBLE_SENTINEL: 'Sentinel',
  LABEL_BUBBLE_MDE: 'MDE',
  LABEL_BUBBLE_MDI: 'MDI',
  LABEL_BUBBLE_LOG: 'Audit Logging',

  CAT_DEVICE: 'Device',                       // Device (Defender XDR)
  CAT_DEVICE_DESC: 'Defender XDR',
  CAT_IDENTITIES: 'Identities',               // Identities (Entra)
  CAT_IDENTITIES_DESC: 'Entra',
  CAT_APPS: 'Apps',                           // Apps (Defender for Cloud Apps)
  CAT_APPS_DESC: 'Defender for Cloud Apps',
  CAT_DATA: 'Data',                           // Data (Purview)
  CAT_DATA_DESC: 'Purview',

  HEADING_RECOMMENDED_ACTIONS: 'Recommended Actions to Boost Score',
  LABEL_REC_MDE_CATEGORY: 'Device (Defender XDR)',
  TXT_REC_MDE_SERVERS: 'Deploy Defender for Servers under the Device (Defender XDR) category to protect hybrid server infrastructure and unmanaged VMs (+16.5% device score).',
  TXT_REC_MDE_SERVERS_EXPAND: 'Expand Defender for Servers Plan 2 coverage under the Device (Defender XDR) category for active server vulnerability assessment (+7.5% device score).',
  TXT_REC_MDI: 'Deploy Microsoft Defender for Identity (MDI) sensors under the Identities (Entra) category (+14.2% identities score).',
  TXT_REC_SENTINEL: 'Connect Microsoft Sentinel workspace for automated threat triage and incident synchronization (+11.8% overall score).',
  TXT_REC_AUDIT: 'Enable Azure Log Analytics Audit Logging under the Data (Purview) category for complete audit trail retention (+9.5% data score).',
  TXT_REC_FULL_STACK: 'Full telemetry stack enabled! Focus on automated Conditional Access policy enforcement and continuous server posture management.',

  HEADING_OVERVIEW_POSTURE: 'Posture Overview & Metrics',
  HEADING_TOP_THREE_LEADERBOARD: 'Leaderboard Top 3',
  HEADING_GLOBAL_AVERAGE: 'Tenant Average Score',
  HEADING_FULL_TELEMETRY: 'Full Security Stack Adoption',
  HEADING_TOP_TENANT: 'Current Leader',
  HEADING_MANAGED_COUNT: 'Total Tenants',
  HEADING_PODIUM: 'Leaderboard Top Performers',
  HEADING_TIER_DISTRIBUTION: 'League & Score Tier Distribution',
  HEADING_TOP_CHART: 'Enterprise Leaderboard Rankings',
  HEADING_CATEGORY_BENCHMARKS: 'Average Category Benchmarks',

  LABEL_LIMIT_TOP: 'Show',
  OPT_LIMIT_15: 'Top 15 (Default)',
  OPT_LIMIT_30: 'Top 30',
  OPT_LIMIT_50: 'Top 50',
  OPT_LIMIT_ALL: 'All Tenants',
  LABEL_USERS: 'Users',
  LABEL_BENCHMARK: 'Benchmark',
  LABEL_ADOPTION_RATE: 'Adoption Rate',
  LABEL_OVERALL_SCORE: 'Overall Score',
  LABEL_TELEMETRY_SUFFIX: 'Telemetry',
  LABEL_FLEET_UNITS: 'Tenants',

  TXT_TERRAIN_COVERAGE: 'Across Managed Tenants',
  TXT_FULL_STACK_STATUS: 'Full Stack Telemetry',

  INPUT_SEARCH_TENANTS: 'Search tenants by name, domain, industry...',
  LABEL_SORT_BY: 'Sort by',
  LABEL_FILTER_TELEMETRY: 'Telemetry Filter',
  LABEL_FILTER_TIER: 'Score League',

  OPT_SORT_SCORE_DESC: 'Overall Score (Highest First)',
  OPT_SORT_SCORE_ASC: 'Overall Score (Lowest First)',
  OPT_SORT_RANK_ASC: 'Leaderboard Rank (1 - #)',
  OPT_SORT_RANK_DESC: 'Leaderboard Rank (# - 1)',
  OPT_SORT_NAME_ASC: 'Tenant Name (A - Z)',
  OPT_SORT_NAME_DESC: 'Tenant Name (Z - A)',
  OPT_SORT_DEVICE_DESC: 'Device (Highest First)',
  OPT_SORT_DEVICE_ASC: 'Device (Lowest First)',
  OPT_SORT_IDENTITIES_DESC: 'Identities (Highest First)',
  OPT_SORT_IDENTITIES_ASC: 'Identities (Lowest First)',
  OPT_SORT_APPS_DESC: 'Apps (Highest First)',
  OPT_SORT_APPS_ASC: 'Apps (Lowest First)',
  OPT_SORT_DATA_DESC: 'Data (Highest First)',
  OPT_SORT_DATA_ASC: 'Data (Lowest First)',

  BTN_SORT_ORDER_DESC: 'Highest First',
  BTN_SORT_ORDER_ASC: 'Lowest First',
  BTN_SORT_ORDER_RANK_ASC: 'Rank #1 - #n',
  BTN_SORT_ORDER_RANK_DESC: 'Rank #n - #1',
  BTN_SORT_ORDER_NAME_ASC: 'A to Z',
  BTN_SORT_ORDER_NAME_DESC: 'Z to A',

  OPT_FILTER_ALL: 'All Tenants',
  OPT_FILTER_FULL_STACK: 'All Capabilities (4 Active)',
  OPT_FILTER_SENTINEL: 'Sentinel Active',
  OPT_FILTER_MDE: 'MDE Active',
  OPT_FILTER_MDI: 'MDI Active',
  OPT_FILTER_AUDIT: 'Audit Logging Active',

  OPT_TIER_ALL: 'All Leagues',
  OPT_TIER_DIAMOND: 'Diamond (90%+)',
  OPT_TIER_GOLD: 'Gold (80-89%)',
  OPT_TIER_SILVER: 'Silver (70-79%)',
  OPT_TIER_BRONZE: 'Bronze (50-69%)',
  OPT_TIER_CRITICAL: 'Critical Attention (<50%)',

  BTN_VIEW_TILES: 'Tile View',
  BTN_VIEW_TABLE: 'Table View',
  BTN_RESET_FILTERS: 'Reset All Filters',
  BTN_INSPECT_TENANT: 'Inspect Tenant',
  BTN_INSPECT: 'Inspect',
  BTN_CLOSE_MODAL: 'Close Details',
  BTN_EXPORT_TENANTS: 'Export Leaderboard (JSON)',
  BTN_EXPORT_SHORT: 'Export',
  BTN_PREVIOUS: 'Previous',
  BTN_NEXT: 'Next',
  TXT_EXPORT_SUCCESS: 'Leaderboard ranking dataset exported successfully',
  TXT_THREAT_SIMULATED: 'Simulated Defender threat signal ingested',
  TXT_NO_TENANTS: 'No Microsoft tenants match the selected filters or search terms.',

  TXT_PAGINATION_SHOWING: 'Showing',
  TXT_PAGINATION_OF: 'of',
  TXT_PAGINATION_TENANTS: 'tenants',
  TXT_PAGE: 'Page',
  TH_RANK: 'Rank',
  TH_TENANT: 'Tenant & Domain',
  TH_SCORE: 'Score',
  TH_ACTION: 'Action',

  HEADING_COMPOSITE_SCORE: 'Terrain Security Posture Composite',
  TXT_POSTURE_SUPERIOR: 'Optimal Defense Posture',
  TXT_POSTURE_MODERATE: 'Degraded Defense Posture',
  TXT_POSTURE_CRITICAL: 'Critical Breach Vulnerability',
  LABEL_ACTIVE_TELEMETRY: 'Active Telemetry',
  STATUS_SENTINEL_ON: 'Ingesting SIEM',
  STATUS_SENTINEL_OFF: 'Not Connected',
  STATUS_MDE_ON: 'EDR Active',
  STATUS_MDE_OFF: 'No Sensor',
  STATUS_MDI_ON: 'Identity Defense',
  STATUS_MDI_OFF: 'Sensor Inactive',
  STATUS_LOG_ON: 'Audit Streaming',
  STATUS_LOG_OFF: 'Logs Disabled',
  HEADING_CATEGORY_BREAKDOWN: 'Domain Posture Vector Breakdown',
  LABEL_MDE_SENSOR: 'MDE Sensor',
  LABEL_DEFENDER_SERVERS: 'Defender for Servers',
  STATUS_ACTIVE: 'Active',
  STATUS_MISSING: 'Missing',
  STATUS_ENROLLED: 'Enrolled',
  STATUS_PENDING: 'Pending Deployment',
  LABEL_REC_IDENTITIES_CATEGORY: 'Identities (Entra)',
  LABEL_REC_SIEM_CATEGORY: 'Sentinel (SIEM)',
  LABEL_REC_AUDIT_CATEGORY: 'Data (Purview)',
  TXT_CLICK_TO_INSPECT: 'Select vector to inspect posture',
  TOOLTIP_SENTINEL_ON: 'Microsoft Sentinel: Connected & Ingesting',
  TOOLTIP_SENTINEL_OFF: 'Microsoft Sentinel: Inactive',
  TOOLTIP_MDE_ON: 'Microsoft Defender for Endpoint: Enrolled',
  TOOLTIP_MDE_OFF: 'Microsoft Defender for Endpoint: Not Deployed',
  TOOLTIP_MDI_ON: 'Microsoft Defender for Identity: Active Sensor',
  TOOLTIP_MDI_OFF: 'Microsoft Defender for Identity: Inactive',
  TOOLTIP_LOG_ON: 'Azure Log Analytics Audit Logging: Stream Active',
  TOOLTIP_LOG_OFF: 'Azure Log Analytics Audit Logging: Disabled',
  TOOLTIP_RANK_1: 'Gold (#1)',
  TOOLTIP_RANK_2: 'Silver (#2)',
  TOOLTIP_RANK_3: 'Bronze (#3)',
  TIER_DIAMOND: 'Diamond Tier',
  TIER_GOLD: 'Gold Tier',
  TIER_SILVER: 'Silver Tier',
  TIER_BRONZE: 'Bronze Tier',
  TIER_CRITICAL: 'Critical Attention Posture',
  FILE_EXPORT_TENANTS_JSON: 'microsoft-tenant-secure-scores.json',
  FILE_EXPORT_SENTINEL_JSON_PREFIX: 'microsoft-sentinel-incidents-',
} as const;

export const APP_STRINGS = {
  APP: {
    HEADING_TITLE: COMMON.APP_TITLE,
  },
  COMMON,
  SIDEBAR,
  HEADER,
  COMMAND_PALETTE,
  SHORTCUTS,
  TOAST,
  VIEWS: {
    HOMEPAGE,
    SETTINGS,
    LOGIN,
    DEBUG,
    MICROSOFT,
    SIDEBAR,
  },
} as const;
