export const APP_STRINGS = {
  app: {
    title: 'Boilerplate App',
  },
  sidebar: {
    heading: 'Boilerplate App',
    navigationLabel: 'Main navigation',
    closeLabel: 'Close sidebar',
    darkModeLabel: 'Dark Mode',
    toggleThemeLabel: 'Toggle dark mode',
    authSection: 'Account',
    loginLabel: 'Login',
    logoutLabel: 'Sign Out',
  },
  header: {
    openSidebarLabel: 'Open sidebar',
    toggleThemeLabel: 'Toggle dark mode',
    userBadge: 'Developer Mode',
  },
  views: {
    homepage: {
      id: 'homepage',
      title: 'Homepage',
      hash: '#homepage',
      heading: 'Welcome to the Homepage',
      description: 'This is the default landing view of the application boilerplate.',
    },
    settings: {
      id: 'settings',
      title: 'Settings',
      hash: '#settings',
      heading: 'Settings',
      description: 'Configure and customize your application settings and preferences.',
    },
    login: {
      id: 'login',
      title: 'Login',
      hash: '#login',
      heading: 'User Authentication',
      description: 'Sign in to access developer privileges and unlock the Debug view.',
      usernameLabel: 'Username',
      passwordLabel: 'Password',
      usernamePlaceholder: 'Enter username (e.g. admin)',
      passwordPlaceholder: 'Enter password',
      submitButton: 'Sign In',
      logoutButton: 'Sign Out',
      goToDebug: 'Open Debug View',
      authNotice: 'Enter any username and password to authenticate.',
      loggedInGreeting: 'You are authenticated as',
      roleDeveloper: 'Developer',
    },
    debug: {
      id: 'debug',
      title: 'Debug',
      hash: '#debug',
      heading: 'Debug & Runtime Diagnostics',
      description: 'Protected view for inspecting runtime state, environment variables, and system metrics.',
      unauthorizedTitle: 'Authentication Required',
      unauthorizedMessage: 'You must be logged in to view the Debug diagnostics dashboard.',
      loginPromptButton: 'Go to Login',
      systemInfoTitle: 'System & Framework',
      activeStateTitle: 'Application State',
      themeState: 'Theme Mode',
      authState: 'Authentication Status',
      authenticatedTrue: 'Authenticated (Active Session)',
      authenticatedFalse: 'Unauthenticated',
      activeAnchor: 'Active URL Anchor',
      registeredViews: 'Registered Views Count',
    },
  },
  theme: {
    storageKey: 'theme',
    dark: 'dark',
    light: 'light',
    prefersDarkQuery: '(prefers-color-scheme: dark)',
  },
  auth: {
    storageKey: 'app_auth_state',
    userStorageKey: 'app_auth_user',
  },
} as const;
