// Centralized application site string constants following component-first naming conventions
export const APP_STRINGS = {
  APP: {
    HEADING_TITLE: 'Boilerplate App',
  },
  SIDEBAR: {
    HEADING_TITLE: 'Boilerplate App',
    NAV_MAIN_ARIA_LABEL: 'Main navigation',
    BTN_CLOSE_ARIA_LABEL: 'Close sidebar',
    LABEL_DARK_MODE: 'Dark Mode',
    SWITCH_THEME_ARIA_LABEL: 'Toggle dark mode',
    BTN_LOGIN_TEXT: 'Sign In',
    BTN_LOGIN_ARIA_LABEL: 'Navigate to login page',
    BTN_LOGOUT_TEXT: 'Sign Out',
    BTN_LOGOUT_ARIA_LABEL: 'Sign out of application',
  },
  HEADER: {
    BTN_OPEN_SIDEBAR_ARIA_LABEL: 'Open sidebar',
    BTN_TOGGLE_THEME_ARIA_LABEL: 'Toggle dark mode',
    BTN_COMMAND_PALETTE_ARIA_LABEL: 'Open command palette',
    BTN_SHORTCUTS_ARIA_LABEL: 'View keyboard shortcuts',
    INPUT_SEARCH_PLACEHOLDER: 'Search or press Ctrl+K...',
    BADGE_DEFAULT_USER: 'User',
    BTN_LOGIN_TEXT: 'Sign In',
    BTN_LOGIN_ARIA_LABEL: 'Navigate to login page',
    BTN_LOGOUT_TEXT: 'Sign Out',
    BTN_LOGOUT_ARIA_LABEL: 'Sign out of application',
  },
  COMMAND_PALETTE: {
    HEADING_TITLE: 'Command Palette',
    INPUT_SEARCH_PLACEHOLDER: 'Type a command or search views...',
    TXT_NO_RESULTS: 'No matching commands found',
    TXT_CATEGORY_NAVIGATION: 'Navigation',
    TXT_CATEGORY_ACTIONS: 'Quick Actions',
    TXT_CATEGORY_APPEARANCE: 'Theme & Appearance',
    TXT_FOOTER_HINT: 'Use arrows to navigate, Enter to select, Esc to close',
    BTN_CLOSE_ARIA_LABEL: 'Close command palette',
  },
  SHORTCUTS: {
    HEADING_TITLE: 'Keyboard Shortcuts',
    TXT_DESCRIPTION: 'Speed up your workflow with these quick keyboard shortcuts.',
    LABEL_GLOBAL_SECTION: 'Global Navigation & Tools',
    LABEL_SHORTCUT_PALETTE: 'Open command palette',
    LABEL_SHORTCUT_SHORTCUTS: 'Show keyboard shortcuts',
    LABEL_SHORTCUT_THEME: 'Toggle dark / light mode',
    LABEL_SHORTCUT_GO_HOME: 'Jump to Homepage',
    LABEL_SHORTCUT_GO_SETTINGS: 'Jump to Settings',
    LABEL_SHORTCUT_GO_DEBUG: 'Jump to Debug (Admin)',
    LABEL_SHORTCUT_GO_LOGIN: 'Jump to Login',
    LABEL_SHORTCUT_CLOSE: 'Close dialog or modal',
    BTN_CLOSE: 'Got It',
    BTN_CLOSE_ARIA_LABEL: 'Close keyboard shortcuts modal',
  },
  TOAST: {
    BTN_DISMISS_ARIA_LABEL: 'Dismiss notification',
    TXT_THEME_DARK: 'Switched to Dark Mode',
    TXT_THEME_LIGHT: 'Switched to Light Mode',
    TXT_ACCENT_CHANGED: 'Accent palette updated to',
    TXT_URL_COPIED: 'Page link copied to clipboard',
    TXT_STORAGE_CLEARED: 'Local storage cache cleared',
    TXT_LOGGED_IN: 'Authenticated successfully',
    TXT_LOGGED_OUT: 'Signed out successfully',
  },
  VIEWS: {
    HOMEPAGE: {
      NAV_ID: 'homepage',
      NAV_TITLE: 'Homepage',
      NAV_HASH: '#homepage',
      HEADING_PAGE: 'Welcome to the Homepage',
      TXT_DESCRIPTION: 'This is the default landing view of the application boilerplate.',
      GREETING_MORNING: 'Good morning',
      GREETING_AFTERNOON: 'Good afternoon',
      GREETING_EVENING: 'Good evening',
      HEADING_QUICK_ACTIONS: 'Quick Actions',
      HEADING_SYSTEM_PULSE: 'System Pulse',
      LABEL_STATUS_AUTH: 'Authentication Status',
      TXT_STATUS_AUTHENTICATED: 'Authenticated',
      TXT_STATUS_NOT_AUTHENTICATED: 'Not Authenticated',
      LABEL_STATUS_THEME: 'Theme Mode',
      LABEL_STATUS_ACCENT: 'Accent Palette',
      BTN_QUICK_SETTINGS: 'Settings',
      BTN_QUICK_PALETTE: 'Command Palette',
      BTN_QUICK_COPY_LINK: 'Copy Page Link',
      BTN_QUICK_DEBUG: 'System Diagnostics',
    },
    SETTINGS: {
      NAV_ID: 'settings',
      NAV_TITLE: 'Settings',
      NAV_HASH: '#settings',
      HEADING_PAGE: 'Settings',
      TXT_DESCRIPTION: 'Configure and customize your application settings and preferences.',
      HEADING_APPEARANCE: 'Appearance & Accent Palette',
      TXT_APPEARANCE_DESC: 'Select your preferred accent theme color across all buttons, tabs, and focus rings.',
      LABEL_ACCENT_PICKER: 'Accent Theme',
      HEADING_FEEDBACK: 'Interactive Feedback & Toasts',
      TXT_FEEDBACK_DESC: 'Test and preview the tactile feedback systems built into the application.',
      BTN_TEST_TOAST: 'Trigger Delight Toast',
      TXT_TEST_TOAST_MESSAGE: 'Here is a delightful toast notification with tactile feedback!',
      HEADING_KEYBOARD_CARD: 'Shortcuts Quick-Reference',
      TXT_KEYBOARD_DESC: 'Press the question mark key anytime to inspect all available hotkeys.',
      BTN_VIEW_SHORTCUTS: 'Open Shortcuts Modal',
    },
    LOGIN: {
      NAV_ID: 'login',
      NAV_TITLE: 'Login',
      NAV_HASH: '#login',
      HEADING_PAGE: 'User Authentication',
      TXT_DESCRIPTION: 'Enter your credentials to access protected diagnostic views.',
      LABEL_USERNAME: 'Username',
      LABEL_PASSWORD: 'Password',
      INPUT_PLACEHOLDER_USERNAME: 'Enter username',
      INPUT_PLACEHOLDER_PASSWORD: 'Enter password',
      BTN_SUBMIT: 'Sign In',
      BTN_LOGOUT: 'Sign Out',
      BTN_GO_TO_DEBUG: 'Open Debug View',
      TXT_AUTH_NOTICE: 'Please provide your authorized credentials to proceed.',
      TXT_INVALID_CREDENTIALS: 'Invalid username or password. Please try again.',
      TXT_LOGGED_IN_GREETING: 'You are authenticated as',
      BTN_CLEAR_STORAGE: 'Clear Local Storage',
      BTN_CLEAR_STORAGE_ARIA_LABEL: 'Clear stored session and preferences from local storage',
    },
    DEBUG: {
      NAV_ID: 'debug',
      NAV_TITLE: 'Debug',
      NAV_HASH: '#debug',
      HEADING_PAGE: 'Debug & Runtime Diagnostics',
      TXT_DESCRIPTION: 'Protected view for inspecting runtime state, environment variables, and system metrics.',
      HEADING_UNAUTHORIZED: 'Authentication Required',
      TXT_UNAUTHORIZED_MESSAGE: 'You must be authenticated to access the diagnostics dashboard.',
      BTN_LOGIN_PROMPT: 'Go to Login',
      HEADING_SYSTEM_INFO: 'System & Framework',
      HEADING_ACTIVE_STATE: 'Application State',
      LABEL_ACTIVE_ANCHOR: 'Active URL Anchor',
      LABEL_AUTH_STATE: 'Authentication Status',
      LABEL_AUTH_ACTIVE: 'Active (True)',
      LABEL_REGISTERED_VIEWS: 'Registered Views Count',
    },
  },
} as const;

